services:
  db:
    container_name: employee_management_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee_management
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - employee_management_data:/data/postgres

volumes:
  employee_management_data: